services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: mp3-goodbooks-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    environment:
      - BOOKS_MODEL_PATH=/app/data/sample/books_model.csv
      - EXPERIMENTS_PATH=/app/results/experiment_results.csv

  gui:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: mp3-goodbooks-gui
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
